name:        snap-auth-cli
version:     "0.1.0.3"
synopsis:    Command-line tool to manage Snap AuthManager database

description: This utility provides command-line interface to user
             database of standard authentication system for
             the Snap web framework. You can create, read and
             update users, set passwords, roles and meta
             information. Currently only JsonFile backend is
             supported. Type `snap-auth-cli -?` to get usage
             information, or see README.md for details.

github: dzhus/snap-auth-cli.git
license: BSD3
author: Dmitry Dzhus
maintainer: dima@dzhus.org
category: Web, Snap
tested-with: GHC==7.6.1

dependencies:
- aeson ==0.6.*
- aeson-pretty ==0.6.*
- base >=4 && <5
- bytestring >=0.9.1 && <0.11
- clientsession ==0.8.*
- cmdargs ==0.10.*
- snap ==0.11.*
- text ==0.11.*
- unordered-containers >=0.1.4 && <0.3
- utf8-string ==0.3.*

executables:
  snap-auth-cli:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
