name:        snap-auth-cli
version:     "0.2"
synopsis:    Command-line tool to manage authentication database for Snap

description: This tool provides a command-line interface to Snap
             authentication database. JSON and SQLite file AuthManager
             backends are supported.

             You can create, read and update users, set passwords,
             roles and meta information. Type `snap-auth-cli -?` to
             get usage information, or see README.md for details.

github: dzhus/snap-auth-cli
license: BSD3
author: Dmitry Dzhus
maintainer: dima@dzhus.org
category: Web, Snap

extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options:
  - -Wall
  - -Wcompat

dependencies:
- aeson
- aeson-pretty
- base <5
- bytestring
- clientsession
- cmdargs
- snap
- snaplet-sqlite-simple
- sqlite-simple
- text
- unordered-containers
- utf8-string

executables:
  snap-auth-cli:
    main: Main.hs
    source-dirs: src
